# Generated by Django 4.2.11 on 2024-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_league_game_date_league_game_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='game_date',
            new_name='league_start_date',
        ),
        migrations.AddField(
            model_name='league',
            name='game_day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2),
        ),
    ]
