# Generated by Django 5.0.3 on 2024-05-04 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player_team_games_played_team_losses_team_ties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.AddField(
            model_name='league',
            name='participating_teams',
            field=models.ManyToManyField(blank=True, related_name='participating_leagues', to='api.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='associated_league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.league'),
        ),
    ]
