# Generated by Django 5.0.3 on 2024-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='max_teams',
            field=models.IntegerField(default=8),
        ),
    ]
